// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gocopper/copper"
	"github.com/gocopper/copper/chttp"
	"github.com/gocopper/copper/csql"
	"github.com/gocopper/examples/hackernews/pkg/app"
	"github.com/gocopper/examples/hackernews/pkg/posts"
	"github.com/gocopper/examples/hackernews/web"
	"github.com/gocopper/examples/hackernews/web/build"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitServer(copperApp *copper.App) (*chttp.Server, error) {
	lifecycle := copperApp.Lifecycle
	loader := copperApp.Config
	config, err := csql.LoadConfig(loader)
	if err != nil {
		return nil, err
	}
	logger := copperApp.Logger
	db, err := csql.NewDBConnection(lifecycle, config, logger)
	if err != nil {
		return nil, err
	}
	txMiddleware := csql.NewTxMiddleware(db, config, logger)
	staticDir := _wireFSValue
	htmlDir := _wireEmbedFSValue
	v := web.HTMLRenderFuncs()
	chttpConfig, err := chttp.LoadConfig(loader)
	if err != nil {
		return nil, err
	}
	newHTMLRendererParams := chttp.NewHTMLRendererParams{
		HTMLDir:     htmlDir,
		StaticDir:   staticDir,
		RenderFuncs: v,
		Config:      chttpConfig,
		Logger:      logger,
	}
	htmlRenderer, err := chttp.NewHTMLRenderer(newHTMLRendererParams)
	if err != nil {
		return nil, err
	}
	readerWriter := chttp.NewReaderWriter(htmlRenderer, chttpConfig, logger)
	newHTMLRouterParams := chttp.NewHTMLRouterParams{
		StaticDir: staticDir,
		RW:        readerWriter,
		Config:    chttpConfig,
	}
	htmlRouter, err := chttp.NewHTMLRouter(newHTMLRouterParams)
	if err != nil {
		return nil, err
	}
	querier := csql.NewQuerier(db, config)
	queries := posts.NewQueries(querier)
	newRouterParams := app.NewRouterParams{
		Posts:  queries,
		RW:     readerWriter,
		Logger: logger,
	}
	router := app.NewRouter(newRouterParams)
	requestLoggerMiddleware := chttp.NewRequestLoggerMiddleware(logger)
	newHTTPHandlerParams := app.NewHTTPHandlerParams{
		DatabaseTxMW:    txMiddleware,
		HTML:            htmlRouter,
		App:             router,
		RequestLoggerMW: requestLoggerMiddleware,
		Logger:          logger,
	}
	handler := app.NewHTTPHandler(newHTTPHandlerParams)
	newServerParams := chttp.NewServerParams{
		Handler:   handler,
		Lifecycle: lifecycle,
		Config:    chttpConfig,
		Logger:    logger,
	}
	server := chttp.NewServer(newServerParams)
	return server, nil
}

var (
	_wireFSValue      = build.StaticDir
	_wireEmbedFSValue = web.HTMLDir
)

// wire.go:

var WireModule = wire.NewSet(copper.WireModule, chttp.WireModule, wire.Struct(new(app.NewHTTPHandlerParams), "*"), app.NewHTTPHandler, app.WireModule, app.NewRouter, wire.Struct(new(app.NewRouterParams), "*"), wire.InterfaceValue(new(chttp.HTMLDir), web.HTMLDir), wire.InterfaceValue(new(chttp.StaticDir), build.StaticDir), web.HTMLRenderFuncs, csql.WireModule)
